In [1]:
import numpy as np

In [2]:
s = 5

In [3]:
s

5

In [4]:
v = np.array([5, -2, 4])

In [5]:
v

array([ 5, -2,  4])

In [7]:
m = np.array([[5, 12, 6],[-3, 0, 14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [9]:
type(m)

numpy.ndarray

In [10]:
type(v)

numpy.ndarray

In [11]:
type(s)

int

In [12]:
s_array = np.array(6)

In [13]:
type(s)

int

In [14]:
type(s_array)

numpy.ndarray

In [15]:
s_array

array(6)

In [16]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

In [18]:
v.reshape(1, 3)

array([[ 5, -2,  4]])

In [19]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [20]:
m.reshape(3,2)

array([[ 5, 12],
       [ 6, -3],
       [ 0, 14]])

In [21]:
m.reshape(2,3)

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [22]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [23]:
s_array.shape

()

In [24]:
m1 = np.array([[5, 12, 6],[-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [25]:
m2 = np.array([[9, 8, 7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
m3 = np.array([m1,m2])

In [28]:
m3

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [29]:
m3.shape

(2, 2, 3)

In [6]:
import numpy as np
m1 = np.array([[5,12,6],[-3,0,14]])
m2 = np.array([[9,8,7],[1,3,5]])
print(m1)
print(m2)

[[ 5 12  6]
 [-3  0 14]]
[[9 8 7]
 [1 3 5]]


In [7]:
m1 + m2

array([[14, 20, 13],
       [-2,  3, 19]])

In [10]:
ma = np.array([[5,3],[-2,4]])
mb = np.array([[7,-5],[3,8]])
ma,mb

(array([[ 5,  3],
        [-2,  4]]),
 array([[ 7, -5],
        [ 3,  8]]))

In [11]:
ma-mb

array([[-2,  8],
       [-5, -4]])

In [12]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [13]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [14]:
V = np.array([1,2,3])
V

array([1, 2, 3])

In [15]:
V.shape

(3,)

In [18]:
reshape_V = V.reshape(1,3)

In [19]:
reshape_V

array([[1, 2, 3]])

In [20]:
reshape_V.T

array([[1],
       [2],
       [3]])

In [30]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [31]:
np.dot(x,y)

-66

In [32]:
x

array([ 2,  8, -4])

In [33]:
5 * x

array([ 10,  40, -20])

In [34]:
x1 = np.array([[5,12,6],[-3,0,14]])
x2 = np.array([[2,-1],[8,0],[3,0]])

In [35]:
np.dot(x1,x2)

array([[124,  -5],
       [ 36,   3]])